# Generated by Django 3.1.6 on 2021-02-09 08:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('glow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image_path',
            field=models.ImageField(default=1, upload_to='pictures/'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('words', models.CharField(max_length=300)),
                ('routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='glow.routine')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
