# Generated by Django 3.1.6 on 2021-02-09 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glow', '0003_auto_20210209_1056'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Skintype',
        ),
    ]
