# Generated by Django 3.1.6 on 2021-02-09 09:39

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('glow', '0004_delete_skintype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='words',
            field=tinymce.models.HTMLField(default='Tell me something', max_length=500),
        ),
    ]
